apiVersion: confi.gurator.com/v1
kind: ResourcefulSet
metadata:
  name: food-processor
spec:
  # We want one instace for each Food in our system
  replicateForResource: Food
  # Name the volume for where to put the food details
  replicationResourceVolume: which-food

  # The paused field can be set to true to pause handling of this ResourcefulSet
  # paused: false

  # Standard selector and template definition, much like for Deployments or StatefulSets:
  selector:
    matchLabels:
      app: food-processor
  template:
    metadata:
      labels:
        app: food-processor
    spec:
      containers:
      - name: food-processor
        image: busybox
        command:
          - 'sh'
          - '-c'
          - 'while true; do
              date;
              for file in /etc/which-food/*; do
                echo $file;
                cat $file;
                echo;
              done;
              sleep 5;
            done'
        # Add a volume so we can know which Food this pod belongs to
        volumeMounts:
          - name: which-food
            mountPath: /etc/which-food
