apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tenants.confi.gurator.com
spec:
  group: confi.gurator.com
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Tenancy kind
      type: string
      description: The kind of tenant this is - MultiTenancies with matching tenancyKind will be replicated per each matching tenant
      JSONPath: .tenancyKind
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            tenancyKind:
              type: string
