apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcefulsets.confi.gurator.com
spec:
  group: confi.gurator.com
  names:
    kind: ResourcefulSet
    listKind: ResourcefulSetList
    plural: resourcefulsets
    singular: resourcefulset
  scope: Namespaced
  version: v1
  subresources:
    status: {}
