apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: multitenancies.confi.gurator.com
spec:
  group: confi.gurator.com
  names:
    kind: MultiTenancy
    listKind: MultiTenancyList
    plural: multitenancies
    singular: multitenancy
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Tenancy kind
      type: string
      description: tenancyKind must match that of each tenant that the MultiTenancy will be replicated for
      JSONPath: .spec.tenancyKind
    - name: Desired
      type: integer
      description: Desired replica count, based on number of renants available
      JSONPath: .status.desiredCount
    - name: Current
      type: integer
      description: Active replica count
      JSONPath: .status.currentCount
    - name: Up-to-date
      type: integer
      description: Active replica count, pointing to up-to-date tenants
      JSONPath: .status.upToDateCount
    - name: Outdated
      type: integer
      description: Active replica count, pointing to outdated tenants (and need to be recreated)
      JSONPath: .status.outdatedCount
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tenancyKind:
              type: string
            tenantResourceVolume:
              type: string
