apiVersion: v1
kind: Namespace
metadata:
  name: resourceful-set

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: resourceful-set
  name: resourceful-set
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resourceful-set
  template:
    metadata:
      labels:
        name: resourceful-set
    spec:
      serviceAccountName: resourceful-set
      containers:
        - name: resourceful-set
          image: configurator/resourceful-set:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - resourceful-set
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "resourceful-set"
