apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: multitenancy
  name: multitenancy
spec:
  replicas: 1
  serviceName: multitenancy
  selector:
    matchLabels:
      name: multitenancy
  template:
    metadata:
      labels:
        name: multitenancy
    spec:
      serviceAccountName: multitenancy
      containers:
        - name: multitenancy
          image: configurator/multitenancy-controller:v1.0.0
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - multitenancy
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multitenancy"
