kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multitenancy
subjects:
- kind: ServiceAccount
  name: multitenancy
  # Replace this with the namespace the operator is deployed in.
  namespace: multitenancy
roleRef:
  kind: ClusterRole
  name: multitenancy
  apiGroup: rbac.authorization.k8s.io
